---
- name: Pulling memcached image
  kolla_docker:
    action: "pull_image"
    common_options: "{{ docker_common_options }}"
    image: "{{ memcached_image_full }}"
  when: inventory_hostname in groups['memcached']
