---
- name: Ensuring config directories exist
  file:
    path: "{{ node_config_directory }}/{{ item }}"
    state: "directory"
    recurse: yes
  with_items:
    - "glance-api"
    - "glance-registry"

- name: Copying over config.json files for services
  template:
    src: "{{ item }}.json.j2"
    dest: "{{ node_config_directory }}/{{ item }}/config.json"
  with_items:
    - "glance-api"
    - "glance-registry"

- name: Copying over glance-*.conf
  merge_configs:
    vars:
      service_name: "{{ item }}"
    sources:
      - "{{ role_path }}/templates/{{ item }}.conf.j2"
      - "/etc/kolla/config/global.conf"
      - "/etc/kolla/config/database.conf"
      - "/etc/kolla/config/messaging.conf"
      - "/etc/kolla/config/glance.conf"
      - "/etc/kolla/config/glance/{{ item }}.conf"
      - "/etc/kolla/config/glance/{{ inventory_hostname }}/{{ item }}.conf"
    dest: "{{ node_config_directory }}/{{ item }}/{{ item }}.conf"
  with_items:
    - "glance-api"
    - "glance-registry"
