---
- name: Creating the Glance service and endpoint
  command: docker exec -t kolla_toolbox /usr/bin/ansible localhost
    -m kolla_keystone_service
    -a "service_name=glance
        service_type=image
        description='Openstack Image'
        endpoint_region={{ openstack_region_name }}
        url='{{ item.url }}'
        interface='{{ item.interface }}'
        region_name={{ openstack_region_name }}
        auth={{ '{{ openstack_glance_auth }}' }}"
    -e "{'openstack_glance_auth':{{ openstack_glance_auth }}}"
  register: glance_endpoint
  changed_when: "{{ glance_endpoint.stdout.find('localhost | SUCCESS => ') != -1 and (glance_endpoint.stdout.split('localhost | SUCCESS => ')[1]|from_json).changed }}"
  until: glance_endpoint.stdout.split()[2] == 'SUCCESS'
  retries: 10
  delay: 5
  run_once: True
  with_items:
    - {'interface': 'admin', 'url': '{{ glance_admin_endpoint }}'}
    - {'interface': 'internal', 'url': '{{ glance_internal_endpoint }}'}
    - {'interface': 'public', 'url': '{{ glance_public_endpoint }}'}

- name: Creating the Glance project, user, and role
  command: docker exec -t kolla_toolbox /usr/bin/ansible localhost
    -m kolla_keystone_user
    -a "project=service
        user=glance
        password={{ glance_keystone_password }}
        role=admin
        region_name={{ openstack_region_name }}
        auth={{ '{{ openstack_glance_auth }}' }}"
    -e "{'openstack_glance_auth':{{ openstack_glance_auth }}}"
  register: glance_user
  changed_when: "{{ glance_user.stdout.find('localhost | SUCCESS => ') != -1 and (glance_user.stdout.split('localhost | SUCCESS => ')[1]|from_json).changed }}"
  until: glance_user.stdout.split()[2] == 'SUCCESS'
  retries: 10
  delay: 5
  run_once: True
