---
- name: Ensuring config directories exist
  file:
    path: "{{ node_config_directory }}/{{ item }}"
    state: "directory"
    recurse: yes
  with_items:
    - "horizon"

- name: Copying over config.json files for services
  template:
    src: "{{ item }}.json.j2"
    dest: "{{ node_config_directory }}/{{ item }}/config.json"
  with_items:
    - "horizon"

- name: Copying over horizon.conf
  template:
    src: "{{ item }}.conf.j2"
    dest: "{{ node_config_directory }}/{{ item }}/{{ item }}.conf"
  with_items:
    - "horizon"

- name: Copying over local_settings
  template:
    src: "local_settings.j2"
    dest: "{{ node_config_directory }}/horizon/local_settings"
