---
- name: Pulling horizon image
  kolla_docker:
    action: "pull_image"
    common_options: "{{ docker_common_options }}"
    image: "{{ horizon_image_full }}"
  when: inventory_hostname in groups['horizon']
