---
- name: Pulling kolla-toolbox image
  kolla_docker:
    action: "pull_image"
    common_options: "{{ docker_common_options }}"
    image: "{{ ansible_image_full }}"

- name: Pulling heka image
  kolla_docker:
    action: "pull_image"
    common_options: "{{ docker_common_options }}"
    image: "{{ heka_image_full }}"

- name: Pulling cron image
  kolla_docker:
    action: "pull_image"
    common_options: "{{ docker_common_options }}"
    image: "{{ cron_image_full }}"
