---
- name: Ensuring config directories exist
  file:
    path: "{{ node_config_directory }}/{{ item }}"
    state: "directory"
    recurse: yes
  with_items:
    - "murano-api"
    - "murano-engine"

- name: Copying over config.json files for services
  template:
    src: "{{ item }}.json.j2"
    dest: "{{ node_config_directory }}/{{ item }}/config.json"
  with_items:
    - "murano-api"
    - "murano-engine"

- name: Copying over murano.conf
  merge_configs:
    vars:
      service_name: "{{ item }}"
    sources:
      - "{{ role_path }}/templates/murano.conf.j2"
      - "/etc/kolla/config/global.conf"
      - "/etc/kolla/config/database.conf"
      - "/etc/kolla/config/messaging.conf"
      - "/etc/kolla/config/murano.conf"
      - "/etc/kolla/config/murano/{{ item }}.conf"
      - "/etc/kolla/config/murano/{{ inventory_hostname }}/murano.conf"
    dest: "{{ node_config_directory }}/{{ item }}/murano.conf"
  with_items:
    - "murano-api"
    - "murano-engine"
