---
- name: Ensuring config directories exist
  file:
    path: "{{ node_config_directory }}/{{ item }}"
    state: "directory"
    recurse: yes
  with_items:
    - "ironic-api"
    - "ironic-conductor"
    - "ironic-inspector"
    - "ironic-pxe"

- name: Copying over config.json files for services
  template:
    src: "{{ item }}.json.j2"
    dest: "{{ node_config_directory }}/{{ item }}/config.json"
  with_items:
    - "ironic-api"
    - "ironic-conductor"
    - "ironic-inspector"
    - "ironic-pxe"

- name: Copying over ironic.conf
  merge_configs:
    vars:
      service_name: "{{ item }}"
    sources:
      - "{{ role_path }}/templates/ironic.conf.j2"
      - "/etc/kolla/config/global.conf"
      - "/etc/kolla/config/database.conf"
      - "/etc/kolla/config/messaging.conf"
      - "/etc/kolla/config/ironic.conf"
      - "/etc/kolla/config/ironic/{{ item }}.conf"
      - "/etc/kolla/config/ironic/{{ inventory_hostname }}/ironic.conf"
    dest: "{{ node_config_directory }}/{{ item }}/ironic.conf"
  with_items:
    - "ironic-api"
    - "ironic-conductor"
    - "ironic-inspector"
