---
- name: Ensuring config directories exist
  file:
    path: "{{ node_config_directory }}/{{ item }}"
    state: "directory"
    recurse: yes
  with_items:
    - "elasticsearch"

- name: Copying over config.json files for services
  template:
    src: "{{ item }}.json.j2"
    dest: "{{ node_config_directory }}/{{ item }}/config.json"
  with_items:
    - "elasticsearch"

- name: Copying over elasticsearch.yml
  template:
    src: "elasticsearch.yml.j2"
    dest: "{{ node_config_directory }}/{{ item }}/{{ item }}.yml"
  with_items:
    - "elasticsearch"
