---
- name: Ensuring config directories exist
  file:
    path: "{{ node_config_directory }}/{{ item }}"
    state: "directory"
    recurse: yes
  with_items:
    - "magnum-api"
    - "magnum-conductor"

- name: Copying over config.json files for services
  template:
    src: "{{ item }}.json.j2"
    dest: "{{ node_config_directory }}/{{ item }}/config.json"
  with_items:
    - "magnum-api"
    - "magnum-conductor"

- name: Copying over magnum.conf
  merge_configs:
    vars:
      service_name: "magnum-api"
    sources:
      - "{{ role_path }}/templates/magnum.conf.j2"
      - "/etc/kolla/config/global.conf"
      - "/etc/kolla/config/database.conf"
      - "/etc/kolla/config/messaging.conf"
      - "/etc/kolla/config/magnum.conf"
      - "/etc/kolla/config/magnum/{{ item }}.conf"
      - "/etc/kolla/config/magnum/{{ inventory_hostname }}/magnum.conf"
    dest: "{{ node_config_directory }}/{{ item }}/magnum.conf"
  with_items:
    - "magnum-api"
    - "magnum-conductor"
