---
- include: do_reconfigure.yml
  serial: "30%"
  when: inventory_hostname in groups['cinder-api']
        or inventory_hostname in groups['cinder-scheduler']
        or inventory_hostname in groups['cinder-volume']
        or inventory_hostname in groups['cinder-backup']
