---
- name: Ensuring kibana config directories exist
  file:
    path: "{{ node_config_directory }}/{{ item }}"
    state: "directory"
    recurse: yes
  with_items:
    - "kibana"

- name: Copying over config.json files for services
  template:
    src: "{{ item }}.json.j2"
    dest: "{{ node_config_directory }}/{{ item }}/config.json"
  with_items:
    - "kibana"

- name: Copying over Kibana configuration file
  template:
    src: "{{ item }}.yml.j2"
    dest: "{{ node_config_directory }}/{{ item }}/{{ item }}.yml"
  with_items:
    - "kibana"
